// Dados de fallback usados quando o projeto Supabase do site ainda não está
// configurado (PUBLIC_SUPABASE_*). São substituídos pelos dados reais assim que
// o projeto novo for criado e seedado (ver ../../supabase/migrations).
//
// Moradas/telefones/e-mails/datas abaixo são REAIS e confirmados pelo dono
// (telefones = WhatsApp; 3 unidades abertas).
// ⚠️ Ainda a confirmar: fotos dos coordenadores e PREÇOS do catálogo.
import type { Office, TeamMember, Service } from './data';

export const fallbackOffices: Office[] = [
  {
    slug: 'albufeira',
    name: 'Albufeira',
    address: 'Rua do MFA, 111 G, 8200-157 Albufeira',
    phone: '351939146298',
    email: 'albufeira@sevens.services',
    whatsapp: '351939146298',
    lat: 37.0891,
    lng: -8.253,
    maps_url: 'https://maps.app.goo.gl/tSGdReHa7WLs3pa79',
    opening_date: '2022-08-01',
    hero_photo: '',
    coordinator_code: 'GR',
    coordinator_name: 'Gabriela Ramos',
    coordinator_role: 'Coordenadora de Processos',
    hours: { 'seg-sex': '09:00–18:00' },
    is_open: true,
    intro: 'A nossa sede, no coração do Algarve.',
  },
  {
    slug: 'faro',
    name: 'Faro',
    address: 'R. Infante Dom Henrique 111, Loja 1, 8000-363 Faro',
    phone: '351928331228',
    email: 'faro@sevens.services',
    whatsapp: '351928331228',
    lat: 37.0194,
    lng: -7.9304,
    maps_url: 'https://maps.app.goo.gl/NHcRMekVhb2rAse88',
    opening_date: '2026-01-01',
    hero_photo: '',
    coordinator_code: 'DS',
    coordinator_name: 'Dayane Silva',
    coordinator_role: 'Coordenadora de Processos',
    hours: { 'seg-sex': '09:00–18:00' },
    is_open: true,
    intro: 'Atendimento na capital de distrito do Algarve.',
  },
  {
    slug: 'porto',
    name: 'Porto',
    address: 'Praça de Mouzinho de Albuquerque 113, 5.º andar, 4100-359 Porto',
    phone: '351928406177',
    email: 'porto@sevens.services',
    whatsapp: '351928406177',
    lat: 41.1496,
    lng: -8.6109,
    maps_url: 'https://maps.app.goo.gl/ANPaRxcM1gh4RVaq8',
    opening_date: '2026-03-01',
    hero_photo: '',
    coordinator_code: '',
    coordinator_name: '',
    coordinator_role: '',
    hours: { 'seg-sex': '09:00–18:00' },
    is_open: true,
    intro: 'A nossa unidade no Norte do país.',
  },
];

export const fallbackTeam: TeamMember[] = [
  { code: 'DJ', name: 'Danilo Jesus', role_label: 'Fundador & CEO', unit: 'Albufeira', photo_url: '', founder: true },
  { code: 'AK', name: 'Ana Kathlyn', role_label: 'Advogada', unit: '', photo_url: '' },
  { code: 'GR', name: 'Gabriela Ramos', role_label: 'Coordenadora de Processos', unit: 'Albufeira', photo_url: '' },
  { code: 'DS', name: 'Dayane Silva', role_label: 'Coordenadora de Processos · Unidade de Faro', unit: 'Faro', photo_url: '' },
];

// Catálogo completo do site (136 serviços, 8 famílias). Fonte de verdade na
// tabela `services` do Supabase; este array é a rede de segurança do build.
export const fallbackServices: Service[] = [
  { code:'AM150', name:'Certidões & Emissões', name_en:'Certificates & Issuance', name_es:'Certificados y Emisiones', category:'aima', family:'AIMA', price:15, price_label:'15 €' },
  { code:'AM151', name:'Contagem Tempo', name_en:'Residence Time Count', name_es:'Cómputo de Tiempo de Residencia', category:'aima', family:'AIMA', price:140, price_label:'140 €', price_obs:'Taxa 23€ - Não Inclusa' },
  { code:'AM152', name:'Defesa - Audiencia Previa', name_en:'Defence - Prior Hearing', name_es:'Defensa - Audiencia Previa', category:'aima', family:'AIMA', price:250, price_label:'a partir de 250 €', requires_consultation:true, action:'book' },
  { code:'AM153', name:'DUC', name_en:'DUC (payment slip)', name_es:'DUC (documento de pago)', category:'aima', family:'AIMA', price:40, price_label:'40 €' },
  { code:'AM154', name:'Estatuto de Igualdade e Direito', name_en:'Equality of Rights Statute', name_es:'Estatuto de Igualdad de Derechos', category:'aima', family:'AIMA', price:80, price_label:'80 €' },
  { code:'AM156', name:'Reagrupamento Familiar', name_en:'Family Reunification', name_es:'Reagrupación Familiar', category:'aima', family:'AIMA', price:150, price_label:'a partir de 150 €', requires_consultation:true, action:'book' },
  { code:'AM157', name:'Renovação A.R - Até 30/06/2025', name_en:'Residence Permit Renewal - Until 30/06/2025', name_es:'Renovación de Residencia - Hasta 30/06/2025', category:'aima', family:'AIMA', price:100, price_label:'100 €' },
  { code:'AM158', name:'Termo de Responsabilidade', name_en:'Statement of Responsibility', name_es:'Declaración de Responsabilidad', category:'aima', family:'AIMA', price:60, price_label:'60 €' },
  { code:'AM159', name:'Upload Documentos', name_en:'Document Upload', name_es:'Subida de Documentos', category:'aima', family:'AIMA', price:60, price_label:'60 €' },
  { code:'AM160', name:'Renovação A.R - pós 30/06/2025', name_en:'Residence Permit Renewal - After 30/06/2025', name_es:'Renovación de Residencia - Tras 30/06/2025', category:'aima', family:'AIMA', price:125, price_label:'125 €', price_obs:'Incluso fotocopia autenticada passaporte, certidões AT & SS' },
  { code:'AM161', name:'Renovação AR - Menores', name_en:'Residence Permit Renewal - Minors', name_es:'Renovación de Residencia - Menores', category:'aima', family:'AIMA', price:140, price_label:'140 €', price_obs:'incluso termo de responsabilidade autenticado, certidões AT & SS' },
  { code:'AM162', name:'Renovação AR - CPLP', name_en:'Residence Permit Renewal - CPLP', name_es:'Renovación de Residencia - CPLP', category:'aima', family:'AIMA', price:100, price_label:'100 €', price_obs:'certidões AT & SS, necessario registo criminal' },
  { code:'AM163', name:'Renovação AR - Longa Duração', name_en:'Residence Permit Renewal - Long-term', name_es:'Renovación de Residencia - Larga Duración', category:'aima', family:'AIMA', price:100, price_label:'100 €' },
  { code:'AM164', name:'Formulario', name_en:'Form', name_es:'Formulario', category:'aima', family:'AIMA', price:100, price_label:'100 €' },
  { code:'AM165', name:'Consultar Processo - Online', name_en:'Case Check - Online', name_es:'Consulta de Expediente - Online', category:'aima', family:'AIMA', price:50, price_label:'50 €' },
  { code:'AM166', name:'Consultar Processo - Presencial', name_en:'Case Check - In person', name_es:'Consulta de Expediente - Presencial', category:'aima', family:'AIMA', price:120, price_label:'120 €' },
  { code:'AM167', name:'Consultoria', name_en:'Consultation', name_es:'Consultoría', category:'aima', family:'AIMA', price:80, price_label:'80 €' },
  { code:'AM168', name:'Carta Registada', name_en:'Registered Letter', name_es:'Carta Certificada', category:'aima', family:'AIMA', price:120, price_label:'120 €', price_obs:'Inclui portes' },
  { code:'AM169', name:'Consultoria/Organização + Upload', name_en:'Consultation/Organisation + Upload', name_es:'Consultoría/Organización + Subida', category:'aima', family:'AIMA', price:120, price_label:'a partir de 120 €', requires_consultation:true, action:'book' },
  { code:'AT101', name:'Atividade - Alteração', name_en:'Activity - Amendment', name_es:'Actividad - Modificación', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT102', name:'Atividade - Cessação', name_en:'Activity - Termination', name_es:'Actividad - Cese', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT103', name:'Atividade - Inicio', name_en:'Activity - Start', name_es:'Actividad - Inicio', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT104', name:'Certidões & Emissões', name_en:'Certificates & Issuance', name_es:'Certificados y Emisiones', category:'a-t-financas', family:'A.T - Finanças', price:15, price_label:'15 €' },
  { code:'AT105', name:'Declaração Periodica de IVA', name_en:'Periodic VAT Return', name_es:'Declaración Periódica de IVA', category:'a-t-financas', family:'A.T - Finanças', price:55, price_label:'55 €' },
  { code:'AT106', name:'IRS', name_en:'IRS (Income Tax)', name_es:'IRS (Renta)', category:'a-t-financas', family:'A.T - Finanças', price:30, price_label:'30 €' },
  { code:'AT107', name:'IUC', name_en:'IUC (Vehicle Tax)', name_es:'IUC (Impuesto de Circulación)', category:'a-t-financas', family:'A.T - Finanças', price:20, price_label:'20 €' },
  { code:'AT108', name:'Morada Fiscal - Alterar', name_en:'Tax Address - Change', name_es:'Domicilio Fiscal - Cambiar', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT109', name:'NIF', name_en:'NIF (Tax Number)', name_es:'NIF (Número Fiscal)', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT111', name:'Plano Prestacional', name_en:'Instalment Plan', name_es:'Plan de Pagos', category:'a-t-financas', family:'A.T - Finanças', price:60, price_label:'60 €' },
  { code:'AT112', name:'Recibo verde - 1x', name_en:'Green Receipt - 1x', name_es:'Recibo Verde - 1x', category:'a-t-financas', family:'A.T - Finanças', price:15, price_label:'15 €' },
  { code:'AT113', name:'Representante Fiscal - Alterar', name_en:'Tax Representative - Change', name_es:'Representante Fiscal - Cambiar', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT114', name:'Representante Fiscal - Inserir', name_en:'Tax Representative - Add', name_es:'Representante Fiscal - Añadir', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT115', name:'Validação de Faturas', name_en:'Invoice Validation', name_es:'Validación de Facturas', category:'a-t-financas', family:'A.T - Finanças', price:40, price_label:'40 €' },
  { code:'AT116', name:'Consultoria', name_en:'Consultation', name_es:'Consultoría', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT117', name:'Atividade - Cessação (com senha do portal)', name_en:'Activity - Termination (with portal password)', name_es:'Actividad - Cese (con clave del portal)', category:'a-t-financas', family:'A.T - Finanças', price:40, price_label:'40 €' },
  { code:'AT118', name:'Atividade - Alteração (com senha do portal)', name_en:'Activity - Amendment (with portal password)', name_es:'Actividad - Modificación (con clave del portal)', category:'a-t-financas', family:'A.T - Finanças', price:40, price_label:'40 €' },
  { code:'AT119', name:'Morada Fiscal - Alterar (morada em portugal e senha do portal)', name_en:'Tax Address - Change (address in PT + portal password)', name_es:'Domicilio Fiscal - Cambiar (domicilio en PT y clave del portal)', category:'a-t-financas', family:'A.T - Finanças', price:50, price_label:'50 €' },
  { code:'BR250', name:'Alistamento Militar', name_en:'Military Enlistment', name_es:'Alistamiento Militar', category:'docs-brasil', family:'Docs. Brasil', price:70, price_label:'70 €' },
  { code:'BR251', name:'Antecedentes Criminais', name_en:'Criminal Record', name_es:'Antecedentes Penales', category:'docs-brasil', family:'Docs. Brasil', price:20, price_label:'20 €' },
  { code:'BR252', name:'Atestado de vida', name_en:'Proof of Life', name_es:'Fe de Vida', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR253', name:'Autorização de Viagem', name_en:'Travel Authorisation', name_es:'Autorización de Viaje', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR254', name:'Casamento', name_en:'Marriage', name_es:'Matrimonio', category:'docs-brasil', family:'Docs. Brasil', price:140, price_label:'140 €' },
  { code:'BR255', name:'Certidão de Nascimento/Casamento + Apostil', name_en:'Birth/Marriage Certificate + Apostille', name_es:'Certificado de Nacimiento/Matrimonio + Apostilla', category:'docs-brasil', family:'Docs. Brasil', price:150, price_label:'150 €' },
  { code:'BR256', name:'Certidão de Nascimento/Casamento 2ª Via digital', name_en:'Birth/Marriage Certificate - Digital 2nd Copy', name_es:'Certificado de Nacimiento/Matrimonio - 2ª Vía digital', category:'docs-brasil', family:'Docs. Brasil', price:100, price_label:'100 €' },
  { code:'BR257', name:'Certidões & Emissões', name_en:'Certificates & Issuance', name_es:'Certificados y Emisiones', category:'docs-brasil', family:'Docs. Brasil', price:15, price_label:'15 €' },
  { code:'BR258', name:'Certificado de Nacionalidade', name_en:'Nationality Certificate', name_es:'Certificado de Nacionalidad', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR259', name:'CPF - Emissão', name_en:'CPF - Issuance', name_es:'CPF - Emisión', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR260', name:'CPF - Regularização', name_en:'CPF - Regularisation', name_es:'CPF - Regularización', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR261', name:'Declaração de Estado civil', name_en:'Marital Status Declaration', name_es:'Declaración de Estado Civil', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR262', name:'Multa Eleitoral', name_en:'Electoral Fine', name_es:'Multa Electoral', category:'docs-brasil', family:'Docs. Brasil', price:20, price_label:'20 €' },
  { code:'BR263', name:'Passaporte', name_en:'Passport', name_es:'Pasaporte', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR264', name:'PB4', name_en:'PB4 (health agreement)', name_es:'PB4 (convenio sanitario)', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR265', name:'Procuração', name_en:'Power of Attorney', name_es:'Poder Notarial', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR266', name:'Registo de Nascimento + 1º Passaporte', name_en:'Birth Registration + 1st Passport', name_es:'Registro de Nacimiento + 1er Pasaporte', category:'docs-brasil', family:'Docs. Brasil', price:140, price_label:'140 €' },
  { code:'BR267', name:'Registro de nascimento', name_en:'Birth Registration', name_es:'Registro de Nacimiento', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR268', name:'Saida Fiscal', name_en:'Tax Exit (Brazil)', name_es:'Salida Fiscal (Brasil)', category:'docs-brasil', family:'Docs. Brasil', price:40, price_label:'40 €' },
  { code:'BR269', name:'Titulo de eleitor - Emissão', name_en:'Voter ID - Issuance', name_es:'Título de Elector - Emisión', category:'docs-brasil', family:'Docs. Brasil', price:90, price_label:'90 €' },
  { code:'BR270', name:'Titulo de eleitor - Regularização', name_en:'Voter ID - Regularisation', name_es:'Título de Elector - Regularización', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR271', name:'Visto - Procura de Trabalho', name_en:'Visa - Job Seeker', name_es:'Visado - Búsqueda de Empleo', category:'docs-brasil', family:'Docs. Brasil', price:800, price_label:'800 €' },
  { code:'CT200', name:'Consultoria', name_en:'Consultation', name_es:'Consultoría', category:'contabilidade', family:'Contabilidade', price:80, price_label:'80 €' },
  { code:'CT201', name:'Empresa', name_en:'Company (accounting)', name_es:'Empresa (contabilidad)', category:'contabilidade', family:'Contabilidade', price:185, price_label:'185 €' },
  { code:'CT202', name:'Não Organizada', name_en:'Simplified Accounting', name_es:'Contabilidad No Organizada', category:'contabilidade', family:'Contabilidade', price:65, price_label:'65 €' },
  { code:'CT203', name:'Organizada', name_en:'Organised Accounting', name_es:'Contabilidad Organizada', category:'contabilidade', family:'Contabilidade', price:150, price_label:'150 €' },
  { code:'IM300', name:'Carta de Condução - 2ª Via', name_en:'Driving Licence - Duplicate', name_es:'Permiso de Conducir - Duplicado', category:'imt', family:'IMT', price:60, price_label:'60 €', price_obs:'Taxa 27€ - Não Inclusa' },
  { code:'IM301', name:'Carta de Condução - Renovação', name_en:'Driving Licence - Renewal', name_es:'Permiso de Conducir - Renovación', category:'imt', family:'IMT', price:60, price_label:'60 €', price_obs:'Taxa 27€ - Não Inclusa' },
  { code:'IM302', name:'Certidões & Emissões', name_en:'Certificates & Issuance', name_es:'Certificados y Emisiones', category:'imt', family:'IMT', price:15, price_label:'15 €' },
  { code:'IM303', name:'Certificado TVDE', name_en:'TVDE Certificate', name_es:'Certificado TVDE', category:'imt', family:'IMT', price:70, price_label:'70 €', price_obs:'Taxa 27€ - Não Inclusa' },
  { code:'IM304', name:'Exame Medico', name_en:'Medical Exam', name_es:'Examen Médico', category:'imt', family:'IMT', price:40, price_label:'40 €' },
  { code:'IM305', name:'Guia de Substituição - Renovação', name_en:'Replacement Slip - Renewal', name_es:'Guía de Sustitución - Renovación', category:'imt', family:'IMT', price:40, price_label:'40 €' },
  { code:'IM307', name:'Troca de Carta Condução Estrangeira', name_en:'Foreign Driving Licence Exchange', name_es:'Canje de Permiso de Conducir Extranjero', category:'imt', family:'IMT', price:100, price_label:'100 €', price_obs:'Não inclui exame medico' },
  { code:'IM308', name:'Troca de Carta Condução Estrangeira + Exame Medico', name_en:'Foreign Driving Licence Exchange + Medical Exam', name_es:'Canje de Permiso de Conducir Extranjero + Examen Médico', category:'imt', family:'IMT', price:140, price_label:'140 €' },
  { code:'IM309', name:'Troca de Carta Condução UE - Completo', name_en:'EU Driving Licence Exchange - Full', name_es:'Canje de Permiso de Conducir UE - Completo', category:'imt', family:'IMT', price:400, price_label:'400 €', price_obs:'clientes europeu que não tem residencia, não inclui nenhuma taxa' },
  { code:'JR350', name:'Ação Judicial - Atraso emissão A.R', name_en:'Lawsuit - Delay in Residence Permit', name_es:'Acción Judicial - Retraso en Residencia', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR351', name:'Ação Judicial - CPLP', name_en:'Lawsuit - CPLP', name_es:'Acción Judicial - CPLP', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR352', name:'Ação Judicial - Estudante', name_en:'Lawsuit - Student', name_es:'Acción Judicial - Estudiante', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR353', name:'Ação Judicial - Indeferimento A.R', name_en:'Lawsuit - Residence Permit Refusal', name_es:'Acción Judicial - Denegación de Residencia', category:'juridico', family:'Juridico', price:1200, price_label:'a partir de 1200 €', requires_consultation:true, action:'book', price_obs:'somente a vista' },
  { code:'JR354', name:'Ação Judicial - MI', name_en:'Lawsuit - Expression of Interest', name_es:'Acción Judicial - Manifestación de Interés', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR355', name:'Ação Judicial - Nacionalidade', name_en:'Lawsuit - Citizenship', name_es:'Acción Judicial - Nacionalidad', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR356', name:'Ação Judicial - Reagrupamento Familiar', name_en:'Lawsuit - Family Reunification', name_es:'Acción Judicial - Reagrupación Familiar', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR357', name:'Ação Judicial - Renovar A.R', name_en:'Lawsuit - Renew Residence Permit', name_es:'Acción Judicial - Renovar Residencia', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR358', name:'Ação Judicial - Visto sem agendamento', name_en:'Lawsuit - Visa without appointment', name_es:'Acción Judicial - Visado sin cita', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR359', name:'Acompanhamento', name_en:'Accompaniment (in person)', name_es:'Acompañamiento', category:'juridico', family:'Juridico', price:250, price_label:'250 €', price_obs:'mais despesa de deslocação' },
  { code:'JR360', name:'Ata - Elaboração', name_en:'Minutes - Drafting', name_es:'Acta - Elaboración', category:'juridico', family:'Juridico', price:80, price_label:'80 €' },
  { code:'JR361', name:'Autorização de viagem para menor', name_en:'Travel Authorisation for Minor', name_es:'Autorización de Viaje para Menor', category:'juridico', family:'Juridico', price:60, price_label:'60 €' },
  { code:'JR362', name:'Casamento - Transcrição*', name_en:'Marriage - Transcription*', name_es:'Matrimonio - Transcripción*', category:'juridico', family:'Juridico', price:450, price_label:'a partir de 450 €', requires_consultation:true, action:'book' },
  { code:'JR363', name:'Consultoria', name_en:'Consultation', name_es:'Consultoría', category:'juridico', family:'Juridico', price:80, price_label:'80 €' },
  { code:'JR364', name:'Contrato', name_en:'Contract', name_es:'Contrato', category:'juridico', family:'Juridico', price:150, price_label:'150 €' },
  { code:'JR365', name:'Autenticação de Documento', name_en:'Document Authentication', name_es:'Autenticación de Documento', category:'juridico', family:'Juridico', price:20, price_label:'20 €' },
  { code:'JR366', name:'Declaração de Alojamento', name_en:'Accommodation Declaration', name_es:'Declaración de Alojamiento', category:'juridico', family:'Juridico', price:30, price_label:'30 €' },
  { code:'JR367', name:'Declaração de Entrada', name_en:'Entry Declaration', name_es:'Declaración de Entrada', category:'juridico', family:'Juridico', price:70, price_label:'70 €' },
  { code:'JR368', name:'Divorcio - Mutuo Consentimento', name_en:'Divorce - Mutual Consent', name_es:'Divorcio - Mutuo Acuerdo', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR369', name:'Divorcio - Transcrição*', name_en:'Divorce - Transcription*', name_es:'Divorcio - Transcripción*', category:'juridico', family:'Juridico', price:1400, price_label:'a partir de 1400 €', requires_consultation:true, action:'book' },
  { code:'JR370', name:'Empresa - Alteração', name_en:'Company - Amendment', name_es:'Empresa - Modificación', category:'juridico', family:'Juridico', price:400, price_label:'400 €' },
  { code:'JR371', name:'Empresa - Constituição', name_en:'Company - Incorporation', name_es:'Empresa - Constitución', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR372', name:'Empresa - Constituição Complexa', name_en:'Company - Complex Incorporation', name_es:'Empresa - Constitución Compleja', category:'juridico', family:'Juridico', price:700, price_label:'700 €' },
  { code:'JR373', name:'Marca/Patente - Defesa', name_en:'Trademark/Patent - Defence', name_es:'Marca/Patente - Defensa', category:'juridico', family:'Juridico', price:300, price_label:'300 €' },
  { code:'JR374', name:'Marca/Patente - Pedido', name_en:'Trademark/Patent - Application', name_es:'Marca/Patente - Solicitud', category:'juridico', family:'Juridico', price:250, price_label:'250 €' },
  { code:'JR375', name:'Nacionalidade PT - Casamento/União de Facto', name_en:'PT Citizenship - Marriage/Civil Partnership', name_es:'Nacionalidad PT - Matrimonio/Unión de Hecho', category:'juridico', family:'Juridico', price:550, price_label:'a partir de 550 €', requires_consultation:true, action:'book', price_obs:'Taxa 250€ - Não Inclusa' },
  { code:'JR376', name:'Nacionalidade PT - Filho/Neto Portugues', name_en:'PT Citizenship - Child/Grandchild of Portuguese', name_es:'Nacionalidad PT - Hijo/Nieto de Portugués', category:'juridico', family:'Juridico', price:550, price_label:'a partir de 550 €', requires_consultation:true, action:'book', price_obs:'Taxa 250€ - Não Inclusa' },
  { code:'JR377', name:'Nacionalidade PT - Pai de Portugues Originario', name_en:'PT Citizenship - Parent of Portuguese by Origin', name_es:'Nacionalidad PT - Padre de Portugués Originario', category:'juridico', family:'Juridico', price:550, price_label:'a partir de 550 €', requires_consultation:true, action:'book', price_obs:'Taxa 250€ - Não Inclusa' },
  { code:'JR378', name:'Nacionalidade PT - Tempo de Residencia', name_en:'PT Citizenship - Residence Time', name_es:'Nacionalidad PT - Tiempo de Residencia', category:'juridico', family:'Juridico', price:550, price_label:'a partir de 550 €', requires_consultation:true, action:'book', price_obs:'Taxa 250€ - Não Inclusa' },
  { code:'JR379', name:'Outros', name_en:'Other', name_es:'Otros', category:'juridico', family:'Juridico', price:100, price_label:'100 €' },
  { code:'JR380', name:'Procuração', name_en:'Power of Attorney', name_es:'Poder Notarial', category:'juridico', family:'Juridico', price:80, price_label:'80 €' },
  { code:'JR381', name:'RCBE', name_en:'RCBE (beneficial owner registry)', name_es:'RCBE (registro de titularidad real)', category:'juridico', family:'Juridico', price:100, price_label:'100 €' },
  { code:'JR382', name:'Autenticação - Reconhecimento de Assinatura', name_en:'Authentication - Signature Recognition', name_es:'Autenticación - Reconocimiento de Firma', category:'juridico', family:'Juridico', price:20, price_label:'20 €' },
  { code:'JR383', name:'Registo Automovel', name_en:'Vehicle Registration', name_es:'Registro de Automóvil', category:'juridico', family:'Juridico', price:100, price_label:'100 €', price_obs:'Taxa 55,30€ - Não Inclusa' },
  { code:'JR385', name:'Tradução Autenticada', name_en:'Certified Translation', name_es:'Traducción Jurada', category:'juridico', family:'Juridico', price:70, price_label:'70 €', price_obs:'2 paginas (documento + apostilamento) + 25€ pagina adic.' },
  { code:'JR386', name:'Casamento', name_en:'Marriage', name_es:'Matrimonio', category:'juridico', family:'Juridico', price:800, price_label:'a partir de 800 €', requires_consultation:true, action:'book' },
  { code:'JR387', name:'Notificação Abandono Voluntario - NAV', name_en:'Voluntary Departure Notice - NAV', name_es:'Notificación de Abandono Voluntario - NAV', category:'juridico', family:'Juridico', price:400, price_label:'400 €', price_obs:'400€ á 600€ (minimo á maximo)' },
  { code:'OT450', name:'Domicilio Fiscal - Corporativo', name_en:'Registered Office - Corporate', name_es:'Domicilio Fiscal - Corporativo', category:'outros', family:'Outros', price:450, price_label:'450 €' },
  { code:'OT451', name:'Domicilio Fiscal - Particular', name_en:'Tax Domicile - Individual', name_es:'Domicilio Fiscal - Particular', category:'outros', family:'Outros', price:180, price_label:'180 €' },
  { code:'OT452', name:'Licenciamento Zero', name_en:'Zero Licensing', name_es:'Licenciamiento Cero', category:'outros', family:'Outros', price:120, price_label:'120 €' },
  { code:'OT453', name:'Matricula escolar', name_en:'School Enrolment', name_es:'Matrícula Escolar', category:'outros', family:'Outros', price:80, price_label:'80 €' },
  { code:'OT454', name:'2ª via', name_en:'Duplicate Copy', name_es:'2ª Vía', category:'outros', family:'Outros', price:20, price_label:'20 €' },
  { code:'OT455', name:'Alojamento Local - Registo', name_en:'Short-term Rental - Registration', name_es:'Alojamiento Local - Registro', category:'outros', family:'Outros', price:100, price_label:'100 €' },
  { code:'OT456', name:'Alvará de obras particulares', name_en:'Private Works Permit', name_es:'Licencia de Obras Particulares', category:'outros', family:'Outros', price:150, price_label:'150 €', price_obs:'Taxa 75€ - Não Inclusa' },
  { code:'OT457', name:'Apostil PT', name_en:'Apostille PT', name_es:'Apostilla PT', category:'outros', family:'Outros', price:50, price_label:'50 €', price_obs:'Taxa Inclusa' },
  { code:'OT458', name:'Certidão de Nascimento/casamento PT', name_en:'PT Birth/Marriage Certificate', name_es:'Certificado de Nacimiento/Matrimonio PT', category:'outros', family:'Outros', price:60, price_label:'60 €' },
  { code:'OT459', name:'Alvará de obras Publicas', name_en:'Public Works Permit', name_es:'Licencia de Obras Públicas', category:'outros', family:'Outros', price:200, price_label:'200 €', price_obs:'Taxa 75€ - Não Inclusa' },
  { code:'SS400', name:'Abono Familia', name_en:'Family Allowance', name_es:'Prestación Familiar', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'SS401', name:'Cartão Europeu de Seguro e Doença', name_en:'European Health Insurance Card', name_es:'Tarjeta Sanitaria Europea', category:'seguranca-social', family:'Segurança Social', price:60, price_label:'60 €' },
  { code:'SS402', name:'Certidões & Emissões', name_en:'Certificates & Issuance', name_es:'Certificados y Emisiones', category:'seguranca-social', family:'Segurança Social', price:15, price_label:'15 €' },
  { code:'SS403', name:'Declaração Trimestral', name_en:'Quarterly Declaration', name_es:'Declaración Trimestral', category:'seguranca-social', family:'Segurança Social', price:40, price_label:'40 €' },
  { code:'SS404', name:'NISS', name_en:'NISS (Social Security No.)', name_es:'NISS (Nº Seguridad Social)', category:'seguranca-social', family:'Segurança Social', price:120, price_label:'120 €' },
  { code:'SS405', name:'Outros', name_en:'Other', name_es:'Otros', category:'seguranca-social', family:'Segurança Social', price:50, price_label:'50 €' },
  { code:'SS406', name:'Plano Prestacional', name_en:'Instalment Plan', name_es:'Plan de Pagos', category:'seguranca-social', family:'Segurança Social', price:60, price_label:'60 €' },
  { code:'SS407', name:'Morada - Alterar', name_en:'Address - Change', name_es:'Domicilio - Cambiar', category:'seguranca-social', family:'Segurança Social', price:30, price_label:'30 €' },
  { code:'SS408', name:'Subsidio Desemprego', name_en:'Unemployment Benefit', name_es:'Subsidio de Desempleo', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'SS409', name:'Abono Pré Natal', name_en:'Prenatal Allowance', name_es:'Prestación Prenatal', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'SS410', name:'Alteração de Dados Cadastrais', name_en:'Personal Data Update', name_es:'Modificación de Datos', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'AM171', name:'Defesa - Audiencia Previa (simples)', name_en:'Defence - Prior Hearing (simple)', name_es:'Defensa - Audiencia Previa (simple)', category:'aima', family:'AIMA', price:125, price_label:'125 €', price_obs:'considerado simples em caso de falta de registo criminal, morada' },
  { code:'JR388', name:'Carta de Despedimento', name_en:'Dismissal Letter', name_es:'Carta de Despido', category:'juridico', family:'Juridico', price:40, price_label:'40 €', price_obs:'modelo padrão de carta de despedimento' },
  { code:'JR389', name:'Carta de Despedimento + Analise do contrato', name_en:'Dismissal Letter + Contract Review', name_es:'Carta de Despido + Análisis del Contrato', category:'juridico', family:'Juridico', price:80, price_label:'80 €', price_obs:'Analise do contrato para elaboração da carta de despedimento' },
  { code:'SS411', name:'Subsidio Desemprego Subsequente', name_en:'Subsequent Unemployment Benefit', name_es:'Subsidio de Desempleo Subsiguiente', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'AT120', name:'Solicitação de senhas', name_en:'Password Request', name_es:'Solicitud de Claves', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €', price_obs:'Anulação de senha atual, e pedido de nova senha (chegará na morada que consta nas finanças)' },
  { code:'AM172', name:'Documentos em Falta', name_en:'Missing Documents', name_es:'Documentos Faltantes', category:'aima', family:'AIMA', price:150, price_label:'150 €', price_obs:'Formulario + Carta Registada' },
];

