// Dados de fallback usados quando o projeto Supabase do site ainda não está
// configurado (PUBLIC_SUPABASE_*). São substituídos pelos dados reais assim que
// o projeto novo for criado e seedado (ver ../../supabase/migrations).
//
// Moradas/telefones/e-mails/datas abaixo são REAIS e confirmados pelo dono
// (telefones = WhatsApp; 3 unidades abertas).
// ⚠️ Ainda a confirmar: fotos dos coordenadores e PREÇOS do catálogo.
import type { Office, TeamMember, Service } from './data';

export const fallbackOffices: Office[] = [
  {
    slug: 'albufeira',
    name: 'Albufeira',
    address: 'Rua do MFA, 111 G, 8200-157 Albufeira',
    phone: '351939146298',
    email: 'albufeira@sevens.services',
    whatsapp: '351939146298',
    lat: 37.0891,
    lng: -8.253,
    maps_url: 'https://maps.app.goo.gl/tSGdReHa7WLs3pa79',
    opening_date: '2022-08-01',
    hero_photo: '',
    coordinator_code: 'GR',
    coordinator_name: 'Gabriela Ramos',
    coordinator_role: 'Coordenadora de Processos',
    hours: { 'seg-sex': '09:00–18:00' },
    is_open: true,
    intro: 'A nossa sede, no coração do Algarve.',
  },
  {
    slug: 'faro',
    name: 'Faro',
    address: 'R. Infante Dom Henrique 111, Loja 1, 8000-363 Faro',
    phone: '351928331228',
    email: 'faro@sevens.services',
    whatsapp: '351928331228',
    lat: 37.0194,
    lng: -7.9304,
    maps_url: 'https://maps.app.goo.gl/NHcRMekVhb2rAse88',
    opening_date: '2026-01-01',
    hero_photo: '',
    coordinator_code: 'DS',
    coordinator_name: 'Dayane Silva',
    coordinator_role: 'Coordenadora de Processos',
    hours: { 'seg-sex': '09:00–18:00' },
    is_open: true,
    intro: 'Atendimento na capital de distrito do Algarve.',
  },
  {
    slug: 'porto',
    name: 'Porto',
    address: 'Praça de Mouzinho de Albuquerque 113, 5.º andar, 4100-359 Porto',
    phone: '351928406177',
    email: 'porto@sevens.services',
    whatsapp: '351928406177',
    lat: 41.1496,
    lng: -8.6109,
    maps_url: 'https://maps.app.goo.gl/ANPaRxcM1gh4RVaq8',
    opening_date: '2026-03-01',
    hero_photo: '',
    coordinator_code: '',
    coordinator_name: '',
    coordinator_role: '',
    hours: { 'seg-sex': '09:00–18:00' },
    is_open: true,
    intro: 'A nossa unidade no Norte do país.',
  },
];

export const fallbackTeam: TeamMember[] = [
  { code: 'DJ', name: 'Danilo Jesus', role_label: 'Fundador & CEO', unit: 'Albufeira', photo_url: '', founder: true },
  { code: 'AK', name: 'Ana Kathlyn', role_label: 'Advogada', unit: '', photo_url: '' },
  { code: 'GR', name: 'Gabriela Ramos', role_label: 'Coordenadora de Processos', unit: 'Albufeira', photo_url: '' },
  { code: 'DS', name: 'Dayane Silva', role_label: 'Coordenadora de Processos · Unidade de Faro', unit: 'Faro', photo_url: '' },
];

// Catálogo completo do site (136 serviços, 8 famílias). Fonte de verdade na
// tabela `services` do Supabase; este array é a rede de segurança do build.
export const fallbackServices: Service[] = [
  { code:'AM150', name:'Certidões & Emissões', category:'aima', family:'AIMA', price:15, price_label:'15 €' },
  { code:'AM151', name:'Contagem Tempo', category:'aima', family:'AIMA', price:140, price_label:'140 €', price_obs:'Taxa 23€ - Não Inclusa' },
  { code:'AM152', name:'Defesa - Audiencia Previa', category:'aima', family:'AIMA', price:250, price_label:'a partir de 250 €', requires_consultation:true, action:'book' },
  { code:'AM153', name:'DUC', category:'aima', family:'AIMA', price:40, price_label:'40 €' },
  { code:'AM154', name:'Estatuto de Igualdade e Direito', category:'aima', family:'AIMA', price:80, price_label:'80 €' },
  { code:'AM156', name:'Reagrupamento Familiar', category:'aima', family:'AIMA', price:150, price_label:'a partir de 150 €', requires_consultation:true, action:'book' },
  { code:'AM157', name:'Renovação A.R - Até 30/06/2025', category:'aima', family:'AIMA', price:100, price_label:'100 €' },
  { code:'AM158', name:'Termo de Responsabilidade', category:'aima', family:'AIMA', price:60, price_label:'60 €' },
  { code:'AM159', name:'Upload Documentos', category:'aima', family:'AIMA', price:60, price_label:'60 €' },
  { code:'AM160', name:'Renovação A.R - pós 30/06/2025', category:'aima', family:'AIMA', price:125, price_label:'125 €', price_obs:'Incluso fotocopia autenticada passaporte, certidões AT & SS' },
  { code:'AM161', name:'Renovação AR - Menores', category:'aima', family:'AIMA', price:140, price_label:'140 €', price_obs:'incluso termo de responsabilidade autenticado, certidões AT & SS' },
  { code:'AM162', name:'Renovação AR - CPLP', category:'aima', family:'AIMA', price:100, price_label:'100 €', price_obs:'certidões AT & SS, necessario registo criminal' },
  { code:'AM163', name:'Renovação AR - Longa Duração', category:'aima', family:'AIMA', price:100, price_label:'100 €' },
  { code:'AM164', name:'Formulario', category:'aima', family:'AIMA', price:100, price_label:'100 €' },
  { code:'AM165', name:'Consultar Processo - Online', category:'aima', family:'AIMA', price:50, price_label:'50 €' },
  { code:'AM166', name:'Consultar Processo - Presencial', category:'aima', family:'AIMA', price:120, price_label:'120 €' },
  { code:'AM167', name:'Consultoria', category:'aima', family:'AIMA', price:80, price_label:'80 €' },
  { code:'AM168', name:'Carta Registada', category:'aima', family:'AIMA', price:120, price_label:'120 €', price_obs:'Inclui portes' },
  { code:'AM169', name:'Consultoria/Organização + Upload', category:'aima', family:'AIMA', price:120, price_label:'a partir de 120 €', requires_consultation:true, action:'book' },
  { code:'AT101', name:'Atividade - Alteração', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT102', name:'Atividade - Cessação', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT103', name:'Atividade - Inicio', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT104', name:'Certidões & Emissões', category:'a-t-financas', family:'A.T - Finanças', price:15, price_label:'15 €' },
  { code:'AT105', name:'Declaração Periodica de IVA', category:'a-t-financas', family:'A.T - Finanças', price:55, price_label:'55 €' },
  { code:'AT106', name:'IRS', category:'a-t-financas', family:'A.T - Finanças', price:30, price_label:'30 €' },
  { code:'AT107', name:'IUC', category:'a-t-financas', family:'A.T - Finanças', price:20, price_label:'20 €' },
  { code:'AT108', name:'Morada Fiscal - Alterar', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT109', name:'NIF', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT111', name:'Plano Prestacional', category:'a-t-financas', family:'A.T - Finanças', price:60, price_label:'60 €' },
  { code:'AT112', name:'Recibo verde - 1x', category:'a-t-financas', family:'A.T - Finanças', price:15, price_label:'15 €' },
  { code:'AT113', name:'Representante Fiscal - Alterar', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT114', name:'Representante Fiscal - Inserir', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT115', name:'Validação de Faturas', category:'a-t-financas', family:'A.T - Finanças', price:40, price_label:'40 €' },
  { code:'AT116', name:'Consultoria', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €' },
  { code:'AT117', name:'Atividade - Cessação (com senha do portal)', category:'a-t-financas', family:'A.T - Finanças', price:40, price_label:'40 €' },
  { code:'AT118', name:'Atividade - Alteração (com senha do portal)', category:'a-t-financas', family:'A.T - Finanças', price:40, price_label:'40 €' },
  { code:'AT119', name:'Morada Fiscal - Alterar (morada em portugal e senha do portal)', category:'a-t-financas', family:'A.T - Finanças', price:50, price_label:'50 €' },
  { code:'BR250', name:'Alistamento Militar', category:'docs-brasil', family:'Docs. Brasil', price:70, price_label:'70 €' },
  { code:'BR251', name:'Antecedentes Criminais', category:'docs-brasil', family:'Docs. Brasil', price:20, price_label:'20 €' },
  { code:'BR252', name:'Atestado de vida', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR253', name:'Autorização de Viagem', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR254', name:'Casamento', category:'docs-brasil', family:'Docs. Brasil', price:140, price_label:'140 €' },
  { code:'BR255', name:'Certidão de Nascimento/Casamento + Apostil', category:'docs-brasil', family:'Docs. Brasil', price:150, price_label:'150 €' },
  { code:'BR256', name:'Certidão de Nascimento/Casamento 2ª Via digital', category:'docs-brasil', family:'Docs. Brasil', price:100, price_label:'100 €' },
  { code:'BR257', name:'Certidões & Emissões', category:'docs-brasil', family:'Docs. Brasil', price:15, price_label:'15 €' },
  { code:'BR258', name:'Certificado de Nacionalidade', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR259', name:'CPF - Emissão', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR260', name:'CPF - Regularização', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR261', name:'Declaração de Estado civil', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR262', name:'Multa Eleitoral', category:'docs-brasil', family:'Docs. Brasil', price:20, price_label:'20 €' },
  { code:'BR263', name:'Passaporte', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR264', name:'PB4', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR265', name:'Procuração', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR266', name:'Registo de Nascimento + 1º Passaporte', category:'docs-brasil', family:'Docs. Brasil', price:140, price_label:'140 €' },
  { code:'BR267', name:'Registro de nascimento', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR268', name:'Saida Fiscal', category:'docs-brasil', family:'Docs. Brasil', price:40, price_label:'40 €' },
  { code:'BR269', name:'Titulo de eleitor - Emissão', category:'docs-brasil', family:'Docs. Brasil', price:90, price_label:'90 €' },
  { code:'BR270', name:'Titulo de eleitor - Regularização', category:'docs-brasil', family:'Docs. Brasil', price:80, price_label:'80 €' },
  { code:'BR271', name:'Visto - Procura de Trabalho', category:'docs-brasil', family:'Docs. Brasil', price:800, price_label:'800 €' },
  { code:'CT200', name:'Consultoria', category:'contabilidade', family:'Contabilidade', price:80, price_label:'80 €' },
  { code:'CT201', name:'Empresa', category:'contabilidade', family:'Contabilidade', price:185, price_label:'185 €' },
  { code:'CT202', name:'Não Organizada', category:'contabilidade', family:'Contabilidade', price:65, price_label:'65 €' },
  { code:'CT203', name:'Organizada', category:'contabilidade', family:'Contabilidade', price:150, price_label:'150 €' },
  { code:'IM300', name:'Carta de Condução - 2ª Via', category:'imt', family:'IMT', price:60, price_label:'60 €', price_obs:'Taxa 27€ - Não Inclusa' },
  { code:'IM301', name:'Carta de Condução - Renovação', category:'imt', family:'IMT', price:60, price_label:'60 €', price_obs:'Taxa 27€ - Não Inclusa' },
  { code:'IM302', name:'Certidões & Emissões', category:'imt', family:'IMT', price:15, price_label:'15 €' },
  { code:'IM303', name:'Certificado TVDE', category:'imt', family:'IMT', price:70, price_label:'70 €', price_obs:'Taxa 27€ - Não Inclusa' },
  { code:'IM304', name:'Exame Medico', category:'imt', family:'IMT', price:40, price_label:'40 €' },
  { code:'IM305', name:'Guia de Substituição - Renovação', category:'imt', family:'IMT', price:40, price_label:'40 €' },
  { code:'IM307', name:'Troca de Carta Condução Estrangeira', category:'imt', family:'IMT', price:100, price_label:'100 €', price_obs:'Não inclui exame medico' },
  { code:'IM308', name:'Troca de Carta Condução Estrangeira + Exame Medico', category:'imt', family:'IMT', price:140, price_label:'140 €' },
  { code:'IM309', name:'Troca de Carta Condução UE - Completo', category:'imt', family:'IMT', price:400, price_label:'400 €', price_obs:'clientes europeu que não tem residencia, não inclui nenhuma taxa' },
  { code:'JR350', name:'Ação Judicial - Atraso emissão A.R', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR351', name:'Ação Judicial - CPLP', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR352', name:'Ação Judicial - Estudante', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR353', name:'Ação Judicial - Indeferimento A.R', category:'juridico', family:'Juridico', price:1200, price_label:'a partir de 1200 €', requires_consultation:true, action:'book', price_obs:'somente a vista' },
  { code:'JR354', name:'Ação Judicial - MI', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR355', name:'Ação Judicial - Nacionalidade', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR356', name:'Ação Judicial - Reagrupamento Familiar', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR357', name:'Ação Judicial - Renovar A.R', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR358', name:'Ação Judicial - Visto sem agendamento', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR359', name:'Acompanhamento', category:'juridico', family:'Juridico', price:250, price_label:'250 €', price_obs:'mais despesa de deslocação' },
  { code:'JR360', name:'Ata - Elaboração', category:'juridico', family:'Juridico', price:80, price_label:'80 €' },
  { code:'JR361', name:'Autorização de viagem para menor', category:'juridico', family:'Juridico', price:60, price_label:'60 €' },
  { code:'JR362', name:'Casamento - Transcrição*', category:'juridico', family:'Juridico', price:450, price_label:'a partir de 450 €', requires_consultation:true, action:'book' },
  { code:'JR363', name:'Consultoria', category:'juridico', family:'Juridico', price:80, price_label:'80 €' },
  { code:'JR364', name:'Contrato', category:'juridico', family:'Juridico', price:150, price_label:'150 €' },
  { code:'JR365', name:'Autenticação de Documento', category:'juridico', family:'Juridico', price:20, price_label:'20 €' },
  { code:'JR366', name:'Declaração de Alojamento', category:'juridico', family:'Juridico', price:30, price_label:'30 €' },
  { code:'JR367', name:'Declaração de Entrada', category:'juridico', family:'Juridico', price:70, price_label:'70 €' },
  { code:'JR368', name:'Divorcio - Mutuo Consentimento', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR369', name:'Divorcio - Transcrição*', category:'juridico', family:'Juridico', price:1400, price_label:'a partir de 1400 €', requires_consultation:true, action:'book' },
  { code:'JR370', name:'Empresa - Alteração', category:'juridico', family:'Juridico', price:400, price_label:'400 €' },
  { code:'JR371', name:'Empresa - Constituição', category:'juridico', family:'Juridico', price:700, price_label:'a partir de 700 €', requires_consultation:true, action:'book' },
  { code:'JR372', name:'Empresa - Constituição Complexa', category:'juridico', family:'Juridico', price:700, price_label:'700 €' },
  { code:'JR373', name:'Marca/Patente - Defesa', category:'juridico', family:'Juridico', price:300, price_label:'300 €' },
  { code:'JR374', name:'Marca/Patente - Pedido', category:'juridico', family:'Juridico', price:250, price_label:'250 €' },
  { code:'JR375', name:'Nacionalidade PT - Casamento/União de Facto', category:'juridico', family:'Juridico', price:550, price_label:'a partir de 550 €', requires_consultation:true, action:'book', price_obs:'Taxa 250€ - Não Inclusa' },
  { code:'JR376', name:'Nacionalidade PT - Filho/Neto Portugues', category:'juridico', family:'Juridico', price:550, price_label:'a partir de 550 €', requires_consultation:true, action:'book', price_obs:'Taxa 250€ - Não Inclusa' },
  { code:'JR377', name:'Nacionalidade PT - Pai de Portugues Originario', category:'juridico', family:'Juridico', price:550, price_label:'a partir de 550 €', requires_consultation:true, action:'book', price_obs:'Taxa 250€ - Não Inclusa' },
  { code:'JR378', name:'Nacionalidade PT - Tempo de Residencia', category:'juridico', family:'Juridico', price:550, price_label:'a partir de 550 €', requires_consultation:true, action:'book', price_obs:'Taxa 250€ - Não Inclusa' },
  { code:'JR379', name:'Outros', category:'juridico', family:'Juridico', price:100, price_label:'100 €' },
  { code:'JR380', name:'Procuração', category:'juridico', family:'Juridico', price:80, price_label:'80 €' },
  { code:'JR381', name:'RCBE', category:'juridico', family:'Juridico', price:100, price_label:'100 €' },
  { code:'JR382', name:'Autenticação - Reconhecimento de Assinatura', category:'juridico', family:'Juridico', price:20, price_label:'20 €' },
  { code:'JR383', name:'Registo Automovel', category:'juridico', family:'Juridico', price:100, price_label:'100 €', price_obs:'Taxa 55,30€ - Não Inclusa' },
  { code:'JR385', name:'Tradução Autenticada', category:'juridico', family:'Juridico', price:70, price_label:'70 €', price_obs:'2 paginas (documento + apostilamento) + 25€ pagina adic.' },
  { code:'JR386', name:'Casamento', category:'juridico', family:'Juridico', price:800, price_label:'a partir de 800 €', requires_consultation:true, action:'book' },
  { code:'JR387', name:'Notificação Abandono Voluntario - NAV', category:'juridico', family:'Juridico', price:400, price_label:'400 €', price_obs:'400€ á 600€ (minimo á maximo)' },
  { code:'OT450', name:'Domicilio Fiscal - Corporativo', category:'outros', family:'Outros', price:450, price_label:'450 €' },
  { code:'OT451', name:'Domicilio Fiscal - Particular', category:'outros', family:'Outros', price:180, price_label:'180 €' },
  { code:'OT452', name:'Licenciamento Zero', category:'outros', family:'Outros', price:120, price_label:'120 €' },
  { code:'OT453', name:'Matricula escolar', category:'outros', family:'Outros', price:80, price_label:'80 €' },
  { code:'OT454', name:'2ª via', category:'outros', family:'Outros', price:20, price_label:'20 €' },
  { code:'OT455', name:'Alojamento Local - Registo', category:'outros', family:'Outros', price:100, price_label:'100 €' },
  { code:'OT456', name:'Alvará de obras particulares', category:'outros', family:'Outros', price:150, price_label:'150 €', price_obs:'Taxa 75€ - Não Inclusa' },
  { code:'OT457', name:'Apostil PT', category:'outros', family:'Outros', price:50, price_label:'50 €', price_obs:'Taxa Inclusa' },
  { code:'OT458', name:'Certidão de Nascimento/casamento PT', category:'outros', family:'Outros', price:60, price_label:'60 €' },
  { code:'OT459', name:'Alvará de obras Publicas', category:'outros', family:'Outros', price:200, price_label:'200 €', price_obs:'Taxa 75€ - Não Inclusa' },
  { code:'SS400', name:'Abono Familia', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'SS401', name:'Cartão Europeu de Seguro e Doença', category:'seguranca-social', family:'Segurança Social', price:60, price_label:'60 €' },
  { code:'SS402', name:'Certidões & Emissões', category:'seguranca-social', family:'Segurança Social', price:15, price_label:'15 €' },
  { code:'SS403', name:'Declaração Trimestral', category:'seguranca-social', family:'Segurança Social', price:40, price_label:'40 €' },
  { code:'SS404', name:'NISS', category:'seguranca-social', family:'Segurança Social', price:120, price_label:'120 €' },
  { code:'SS405', name:'Outros', category:'seguranca-social', family:'Segurança Social', price:50, price_label:'50 €' },
  { code:'SS406', name:'Plano Prestacional', category:'seguranca-social', family:'Segurança Social', price:60, price_label:'60 €' },
  { code:'SS407', name:'Morada - Alterar', category:'seguranca-social', family:'Segurança Social', price:30, price_label:'30 €' },
  { code:'SS408', name:'Subsidio Desemprego', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'SS409', name:'Abono Pré Natal', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'SS410', name:'Alteração de Dados Cadastrais', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'AM171', name:'Defesa - Audiencia Previa (simples)', category:'aima', family:'AIMA', price:125, price_label:'125 €', price_obs:'considerado simples em caso de falta de registo criminal, morada' },
  { code:'JR388', name:'Carta de Despedimento', category:'juridico', family:'Juridico', price:40, price_label:'40 €', price_obs:'modelo padrão de carta de despedimento' },
  { code:'JR389', name:'Carta de Despedimento + Analise do contrato', category:'juridico', family:'Juridico', price:80, price_label:'80 €', price_obs:'Analise do contrato para elaboração da carta de despedimento' },
  { code:'SS411', name:'Subsidio Desemprego Subsequente', category:'seguranca-social', family:'Segurança Social', price:80, price_label:'80 €' },
  { code:'AT120', name:'Solicitação de senhas', category:'a-t-financas', family:'A.T - Finanças', price:80, price_label:'80 €', price_obs:'Anulação de senha atual, e pedido de nova senha (chegará na morada que consta nas finanças)' },
  { code:'AM172', name:'Documentos em Falta', category:'aima', family:'AIMA', price:150, price_label:'150 €', price_obs:'Formulario + Carta Registada' },
];

